name: Deploy Node App to GCE VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Connect and Deploy to GCE VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCE_VM_HOST }}
        username: ${{ secrets.GCE_VM_USER }}
        key: ${{ secrets.GCE_VM_SSH_KEY }}
        script: |
          cd ~/AgenticDevOpsDemo
          git pull origin main
          npm install
          pkill node || true
          node app.js > out.log 2>&1
